// This file is auto-generated by @hey-api/openapi-ts

export { getWeatherForecast, type Options } from './sdk.gen';
export type { ClientOptions, GetWeatherForecastData, GetWeatherForecastResponse, GetWeatherForecastResponses, WeatherForecast } from './types.gen';
