// This file is auto-generated by @hey-api/openapi-ts

export const AvailabilitySchema = {
  required: ["userName", "schedule"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    guid: {
      type: "string",
      format: "uuid",
    },
    availabilitySlots: {
      type: "array",
      items: {
        type: "string",
        format: "date-time",
      },
    },
    userName: {
      maxLength: 64,
      type: "string",
    },
    userEmail: {
      maxLength: 256,
      type: ["null", "string"],
    },
    preferences: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/AvailabilityPreferences",
        },
      ],
    },
    formAnswers: {
      type: "array",
      items: {
        $ref: "#/components/schemas/FormQuestionAnswer",
      },
    },
    schedule: {
      $ref: "#/components/schemas/Schedule",
    },
  },
} as const;

export const AvailabilityPreferencesSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
  },
} as const;

export const FormSchema = {
  required: ["schedule"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    questions: {
      type: "array",
      items: {
        $ref: "#/components/schemas/FormQuestion",
      },
    },
    schedule: {
      $ref: "#/components/schemas/Schedule",
    },
  },
} as const;

export const FormQuestionSchema = {
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    questionText: {
      maxLength: 512,
      type: "string",
    },
    type: {
      $ref: "#/components/schemas/QuestionType",
    },
    options: {
      type: "array",
      items: {
        $ref: "#/components/schemas/QuestionOptions",
      },
    },
  },
} as const;

export const FormQuestionAnswerSchema = {
  required: ["question", "answerText"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    formQuestionId: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    answerId: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    question: {
      $ref: "#/components/schemas/FormQuestion",
    },
    answerText: {
      type: "string",
    },
  },
} as const;

export const QuestionOptionsSchema = {
  required: ["optionText"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    optionText: {
      maxLength: 64,
      type: "string",
    },
    sortOrder: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const QuestionTypeSchema = {
  type: "integer",
} as const;

export const ScheduleSchema = {
  required: ["auth0UserId", "name", "dateCoverage", "startTime", "endTime", "schedulePreferences"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    guid: {
      type: "string",
      format: "uuid",
    },
    auth0UserId: {
      maxLength: 256,
      type: "string",
    },
    name: {
      maxLength: 256,
      type: "string",
    },
    dateCoverage: {
      type: "array",
      items: {
        type: "string",
        format: "date",
      },
    },
    startTime: {
      type: "string",
      format: "time",
    },
    endTime: {
      type: "string",
      format: "time",
    },
    form: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/Form",
        },
      ],
    },
    formId: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["null", "integer", "string"],
      format: "int32",
    },
    shiftAssignments: {
      type: ["null", "array"],
      items: {
        $ref: "#/components/schemas/ShiftAssignment",
      },
    },
    schedulePreferences: {
      $ref: "#/components/schemas/SchedulePreferences",
    },
  },
} as const;

export const ScheduleDtoSchema = {
  required: ["dateCoverage", "startTime", "endTime", "schedulePreferences", "name"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["null", "integer", "string"],
      format: "int32",
    },
    guid: {
      type: ["null", "string"],
      format: "uuid",
    },
    dateCoverage: {
      type: "array",
      items: {
        type: "string",
        format: "date",
      },
    },
    startTime: {
      type: "string",
      format: "time",
    },
    endTime: {
      type: "string",
      format: "time",
    },
    shiftAssignments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ShiftAssignment",
      },
    },
    schedulePreferences: {
      $ref: "#/components/schemas/SchedulePreferences",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const SchedulePreferencesSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    minutesPerSlot: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    shiftIntervals: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    usersPerShift: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    maximumShiftDurationMinutes: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    maximumShiftsPerWorker: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const ScheduleUpdateDtoSchema = {
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["null", "integer", "string"],
      format: "int32",
    },
    guid: {
      type: ["null", "string"],
      format: "uuid",
    },
    shiftAssignments: {
      type: ["null", "array"],
      items: {
        $ref: "#/components/schemas/ShiftAssignment",
      },
    },
    schedulePreferences: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/SchedulePreferences",
        },
      ],
    },
    name: {
      type: ["null", "string"],
    },
  },
} as const;

export const ShiftAssignmentSchema = {
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    startTime: {
      type: "string",
      format: "date-time",
    },
    endTime: {
      type: "string",
      format: "date-time",
    },
    availability: {
      $ref: "#/components/schemas/Availability",
    },
    schedule: {
      $ref: "#/components/schemas/Schedule",
    },
  },
} as const;
