// This file is auto-generated by @hey-api/openapi-ts

export const ScheduleDtoSchema = {
  required: ["dateCoverage", "startTime", "endTime", "schedulePreferences"],
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["null", "integer", "string"],
      format: "int32",
    },
    guid: {
      type: ["null", "string"],
      format: "uuid",
    },
    dateCoverage: {
      type: "array",
      items: {
        type: "string",
        format: "date",
      },
    },
    startTime: {
      type: "string",
      format: "time",
    },
    endTime: {
      type: "string",
      format: "time",
    },
    shiftAssignments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ShiftAssignment",
      },
    },
    schedulePreferences: {
      $ref: "#/components/schemas/SchedulePreferences",
    },
  },
} as const;

export const SchedulePreferencesSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    minutesPerSlot: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;

export const ShiftAssignmentSchema = {
  type: "object",
  properties: {
    id: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    startTime: {
      type: "string",
      format: "date-time",
    },
    endTime: {
      type: "string",
      format: "date-time",
    },
  },
} as const;
