// This file is auto-generated by @hey-api/openapi-ts

export const WeatherForecastSchema = {
  required: ["date", "temperatureC", "summary"],
  type: "object",
  properties: {
    date: {
      type: "string",
      format: "date",
    },
    temperatureC: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
    summary: {
      type: ["null", "string"],
    },
    temperatureF: {
      pattern: "^-?(?:0|[1-9]\\d*)$",
      type: ["integer", "string"],
      format: "int32",
    },
  },
} as const;
