// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteApiScheduleByGuidData,
  DeleteApiScheduleByGuidResponses,
  GetApiAvailabilityByGuidExistsData,
  GetApiAvailabilityByGuidExistsResponses,
  GetApiAvailabilityByGuidGenerateLinkData,
  GetApiAvailabilityByGuidGenerateLinkResponses,
  GetApiAvailabilityPublicData,
  GetApiAvailabilityPublicResponses,
  GetApiClaimsData,
  GetApiClaimsResponses,
  GetApiPrivateData,
  GetApiPrivateResponses,
  GetApiPrivateScopedData,
  GetApiPrivateScopedResponses,
  GetApiPublicData,
  GetApiPublicResponses,
  GetApiScheduleByGuidData,
  GetApiScheduleByGuidGenerateScheduleData,
  GetApiScheduleByGuidGenerateScheduleResponses,
  GetApiScheduleByGuidResponses,
  GetApiScheduleData,
  GetApiScheduleResponses,
  PatchApiScheduleByGuidData,
  PatchApiScheduleByGuidResponses,
  PostApiScheduleData,
  PostApiScheduleResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiPublic = <ThrowOnError extends boolean = false>(options?: Options<GetApiPublicData, ThrowOnError>) =>
  (options?.client ?? client).get<GetApiPublicResponses, unknown, ThrowOnError>({ url: "/api/public", ...options });

export const getApiPrivate = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrivateData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiPrivateResponses, unknown, ThrowOnError>({ url: "/api/private", ...options });

export const getApiPrivateScoped = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrivateScopedData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiPrivateScopedResponses, unknown, ThrowOnError>({
    url: "/api/private-scoped",
    ...options,
  });

export const getApiClaims = <ThrowOnError extends boolean = false>(options?: Options<GetApiClaimsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetApiClaimsResponses, unknown, ThrowOnError>({ url: "/api/claims", ...options });

export const getApiAvailabilityPublic = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAvailabilityPublicData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiAvailabilityPublicResponses, unknown, ThrowOnError>({
    url: "/api/availability/public",
    ...options,
  });

export const getApiAvailabilityByGuidExists = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAvailabilityByGuidExistsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiAvailabilityByGuidExistsResponses, unknown, ThrowOnError>({
    url: "/api/availability/{guid}/exists",
    ...options,
  });

export const getApiAvailabilityByGuidGenerateLink = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAvailabilityByGuidGenerateLinkData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiAvailabilityByGuidGenerateLinkResponses, unknown, ThrowOnError>({
    url: "/api/availability/{guid}/generateLink",
    ...options,
  });

export const deleteApiScheduleByGuid = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiScheduleByGuidData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApiScheduleByGuidResponses, unknown, ThrowOnError>({
    url: "/api/schedule/{guid}",
    ...options,
  });

export const getApiScheduleByGuid = <ThrowOnError extends boolean = false>(
  options: Options<GetApiScheduleByGuidData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiScheduleByGuidResponses, unknown, ThrowOnError>({
    url: "/api/schedule/{guid}",
    ...options,
  });

export const patchApiScheduleByGuid = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiScheduleByGuidData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PatchApiScheduleByGuidResponses, unknown, ThrowOnError>({
    url: "/api/schedule/{guid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiSchedule = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiScheduleData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiScheduleResponses, unknown, ThrowOnError>({ url: "/api/schedule", ...options });

export const postApiSchedule = <ThrowOnError extends boolean = false>(
  options: Options<PostApiScheduleData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiScheduleResponses, unknown, ThrowOnError>({
    url: "/api/schedule",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiScheduleByGuidGenerateSchedule = <ThrowOnError extends boolean = false>(
  options: Options<GetApiScheduleByGuidGenerateScheduleData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiScheduleByGuidGenerateScheduleResponses, unknown, ThrowOnError>({
    url: "/api/schedule/{guid}/generateSchedule",
    ...options,
  });
