// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetApiClaimsData,
  GetApiClaimsResponses,
  GetApiPrivateData,
  GetApiPrivateResponses,
  GetApiPrivateScopedData,
  GetApiPrivateScopedResponses,
  GetApiPublicData,
  GetApiPublicResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiPublic = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPublicData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiPublicResponses, unknown, ThrowOnError>(
    { url: "/api/public", ...options },
  );

export const getApiPrivate = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrivateData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiPrivateResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/private", ...options });

export const getApiPrivateScoped = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPrivateScopedData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiPrivateScopedResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/private-scoped", ...options });

export const getApiClaims = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiClaimsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiClaimsResponses, unknown, ThrowOnError>(
    { url: "/api/claims", ...options },
  );
