// This file is auto-generated by @hey-api/openapi-ts

import type { GetWeatherForecastResponse } from './types.gen';

const weatherForecastSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

export const getWeatherForecastResponseTransformer = async (data: any): Promise<GetWeatherForecastResponse> => {
    data = data.map((item: any) => weatherForecastSchemaResponseTransformer(item));
    return data;
};
