// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Availability = {
  id?: number | string;
  guid?: string;
  availabilitySlots?: Array<Date>;
  userName: string;
  userEmail?: null | string;
  preferences?: null | AvailabilityPreferences;
  formAnswers?: Array<FormQuestionAnswer>;
};

export type AvailabilityPreferences = {
  id?: string;
};

export type FormQuestion = {
  id?: number | string;
  questionText?: string;
  type?: QuestionType;
  options?: Array<QuestionOptions>;
};

export type FormQuestionAnswer = {
  id?: number | string;
  formQuestionId?: number | string;
  answerId?: number | string;
  question: FormQuestion;
  answerText: string;
};

export type QuestionOptions = {
  id?: number | string;
  optionText: string;
  sortOrder?: number | string;
};

export type QuestionType = number;

export type ScheduleDto = {
  id?: null | number | string;
  guid?: null | string;
  dateCoverage: Array<Date>;
  startTime: string;
  endTime: string;
  shiftAssignments?: Array<ShiftAssignment>;
  schedulePreferences: SchedulePreferences;
  name: string;
};

export type SchedulePreferences = {
  id?: string;
  minutesPerSlot?: number | string;
  shiftIntervals?: number | string;
  usersPerShift?: number | string;
  maximumShiftDurationMinutes?: number | string;
  maximumShiftsPerWorker?: number | string;
};

export type ScheduleUpdateDto = {
  id?: null | number | string;
  guid?: null | string;
  shiftAssignments?: null | Array<ShiftAssignment>;
  schedulePreferences?: null | SchedulePreferences;
  name?: null | string;
};

export type ShiftAssignment = {
  id?: number | string;
  startTime?: Date;
  endTime?: Date;
  availability?: null | Availability;
};

export type GetApiPublicData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/public";
};

export type GetApiPublicResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiPrivateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/private";
};

export type GetApiPrivateResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiPrivateScopedData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/private-scoped";
};

export type GetApiPrivateScopedResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiClaimsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/claims";
};

export type GetApiClaimsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAvailabilityPublicData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/availability/public";
};

export type GetApiAvailabilityPublicResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAvailabilityByGuidExistsData = {
  body?: never;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/availability/{guid}/exists";
};

export type GetApiAvailabilityByGuidExistsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAvailabilityByGuidGenerateLinkData = {
  body?: never;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/availability/{guid}/generateLink";
};

export type GetApiAvailabilityByGuidGenerateLinkResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiScheduleByGuidData = {
  body?: never;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/schedule/{guid}";
};

export type DeleteApiScheduleByGuidResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiScheduleByGuidData = {
  body?: never;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/schedule/{guid}";
};

export type GetApiScheduleByGuidResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PatchApiScheduleByGuidData = {
  body: ScheduleUpdateDto;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/schedule/{guid}";
};

export type PatchApiScheduleByGuidResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiScheduleData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/schedule";
};

export type GetApiScheduleResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiScheduleData = {
  body: ScheduleDto;
  path?: never;
  query?: never;
  url: "/api/schedule";
};

export type PostApiScheduleResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiScheduleByGuidGenerateScheduleData = {
  body?: never;
  path: {
    guid: string;
  };
  query?: never;
  url: "/api/schedule/{guid}/generateSchedule";
};

export type GetApiScheduleByGuidGenerateScheduleResponses = {
  /**
   * OK
   */
  200: unknown;
};
