// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiPublicData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/public";
};

export type GetApiPublicResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiPrivateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/private";
};

export type GetApiPrivateResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiPrivateScopedData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/private-scoped";
};

export type GetApiPrivateScopedResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiClaimsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/claims";
};

export type GetApiClaimsResponses = {
  /**
   * OK
   */
  200: unknown;
};
