// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zAvailabilityPreferences = z.object({
  id: z.optional(z.uuid()),
});

export const zQuestionOptions = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  optionText: z.string().max(64),
  sortOrder: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
});

export const zQuestionType = z.int();

export const zFormQuestion = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  questionText: z.optional(z.string().max(512)),
  type: z.optional(zQuestionType),
  options: z.optional(z.array(zQuestionOptions)),
});

export const zFormQuestionAnswer = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  formQuestionId: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  answerId: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  question: zFormQuestion,
  answerText: z.string(),
});

export const zAvailability = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  guid: z.optional(z.uuid()),
  availabilitySlots: z.optional(z.array(z.iso.datetime())),
  userName: z.string().max(64),
  userEmail: z.optional(z.union([z.null(), z.string().max(256)])),
  preferences: z.optional(z.union([z.null(), zAvailabilityPreferences])),
  formAnswers: z.optional(z.array(zFormQuestionAnswer)),
});

export const zSchedulePreferences = z.object({
  id: z.optional(z.uuid()),
  minutesPerSlot: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  shiftIntervals: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  usersPerShift: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  maximumShiftDurationMinutes: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  maximumShiftsPerWorker: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
});

export const zShiftAssignment = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  startTime: z.optional(z.iso.datetime()),
  endTime: z.optional(z.iso.datetime()),
  availability: z.optional(z.union([z.null(), zAvailability])),
});

export const zScheduleDto = z.object({
  id: z.optional(
    z.union([
      z.null(),
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  guid: z.optional(z.union([z.null(), z.uuid()])),
  dateCoverage: z.array(z.iso.date()),
  startTime: z.iso.time(),
  endTime: z.iso.time(),
  shiftAssignments: z.optional(z.array(zShiftAssignment)),
  schedulePreferences: zSchedulePreferences,
  name: z.string(),
});

export const zScheduleUpdateDto = z.object({
  id: z.optional(
    z.union([
      z.null(),
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  guid: z.optional(z.union([z.null(), z.uuid()])),
  shiftAssignments: z.optional(z.union([z.null(), z.array(zShiftAssignment)])),
  schedulePreferences: z.optional(z.union([z.null(), zSchedulePreferences])),
  name: z.optional(z.union([z.null(), z.string()])),
});

export const zGetApiPublicData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiPrivateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiPrivateScopedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiClaimsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityPublicData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityByGuidExistsData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityByGuidGenerateLinkData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zDeleteApiScheduleByGuidData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiScheduleByGuidData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zPatchApiScheduleByGuidData = z.object({
  body: zScheduleUpdateDto,
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiScheduleData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiScheduleData = z.object({
  body: zScheduleDto,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiScheduleByGuidGenerateScheduleData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});
