// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zSchedulePreferences = z.object({
  id: z.optional(z.uuid()),
  minutesPerSlot: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  shiftIntervals: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  usersPerShift: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  maximumShiftDurationMinutes: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  maximumShiftsPerWorker: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
});

export const zShiftAssignment = z.object({
  id: z.optional(
    z.union([
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  startTime: z.optional(z.iso.datetime()),
  endTime: z.optional(z.iso.datetime()),
});

export const zScheduleDto = z.object({
  id: z.optional(
    z.union([
      z.null(),
      z
        .int()
        .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
        .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ]),
  ),
  guid: z.optional(z.union([z.null(), z.uuid()])),
  dateCoverage: z.array(z.iso.date()),
  startTime: z.iso.time(),
  endTime: z.iso.time(),
  shiftAssignments: z.optional(z.array(zShiftAssignment)),
  schedulePreferences: zSchedulePreferences,
  name: z.string(),
});

export const zGetApiPublicData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiPrivateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiPrivateScopedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiClaimsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityPublicData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityByGuidExistsData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiAvailabilityByGuidGenerateLinkData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiSchedulePublicData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiScheduleClaimsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiScheduleByGuidData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiScheduleByGuidData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zPutApiScheduleByGuidData = z.object({
  body: zScheduleDto,
  path: z.object({
    guid: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetApiScheduleData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiScheduleData = z.object({
  body: zScheduleDto,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});
