// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  deleteApiScheduleByGuid,
  get,
  getApiAvailabilityByGuidExists,
  getApiAvailabilityPublic,
  getApiClaims,
  getApiPrivate,
  getApiPrivateScoped,
  getApiPublic,
  getApiScheduleByGuid,
  getApiScheduleClaims,
  getApiSchedulePublic,
  type Options,
  postApiSchedule,
  putApiScheduleByGuid,
} from "../sdk.gen";
import type {
  DeleteApiScheduleByGuidData,
  GetApiAvailabilityByGuidExistsData,
  GetApiAvailabilityPublicData,
  GetApiClaimsData,
  GetApiPrivateData,
  GetApiPrivateScopedData,
  GetApiPublicData,
  GetApiScheduleByGuidData,
  GetApiScheduleClaimsData,
  GetApiSchedulePublicData,
  GetData,
  PostApiScheduleData,
  PutApiScheduleByGuidData,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiPublicQueryKey = (options?: Options<GetApiPublicData>) =>
  createQueryKey("getApiPublic", options);

export const getApiPublicOptions = (options?: Options<GetApiPublicData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPublicQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPublicQueryKey(options),
  });

export const getApiPrivateQueryKey = (options?: Options<GetApiPrivateData>) =>
  createQueryKey("getApiPrivate", options);

export const getApiPrivateOptions = (options?: Options<GetApiPrivateData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPrivateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateQueryKey(options),
  });

export const getApiPrivateScopedQueryKey = (
  options?: Options<GetApiPrivateScopedData>,
) => createQueryKey("getApiPrivateScoped", options);

export const getApiPrivateScopedOptions = (
  options?: Options<GetApiPrivateScopedData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPrivateScopedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivateScoped({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateScopedQueryKey(options),
  });

export const getApiClaimsQueryKey = (options?: Options<GetApiClaimsData>) =>
  createQueryKey("getApiClaims", options);

export const getApiClaimsOptions = (options?: Options<GetApiClaimsData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiClaimsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClaims({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiClaimsQueryKey(options),
  });

export const getApiAvailabilityPublicQueryKey = (
  options?: Options<GetApiAvailabilityPublicData>,
) => createQueryKey("getApiAvailabilityPublic", options);

export const getApiAvailabilityPublicOptions = (
  options?: Options<GetApiAvailabilityPublicData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiAvailabilityPublicQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAvailabilityPublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAvailabilityPublicQueryKey(options),
  });

export const getApiAvailabilityByGuidExistsQueryKey = (
  options: Options<GetApiAvailabilityByGuidExistsData>,
) => createQueryKey("getApiAvailabilityByGuidExists", options);

export const getApiAvailabilityByGuidExistsOptions = (
  options: Options<GetApiAvailabilityByGuidExistsData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiAvailabilityByGuidExistsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAvailabilityByGuidExists({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAvailabilityByGuidExistsQueryKey(options),
  });

export const getApiSchedulePublicQueryKey = (
  options?: Options<GetApiSchedulePublicData>,
) => createQueryKey("getApiSchedulePublic", options);

export const getApiSchedulePublicOptions = (
  options?: Options<GetApiSchedulePublicData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiSchedulePublicQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSchedulePublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiSchedulePublicQueryKey(options),
  });

export const getApiScheduleClaimsQueryKey = (
  options?: Options<GetApiScheduleClaimsData>,
) => createQueryKey("getApiScheduleClaims", options);

export const getApiScheduleClaimsOptions = (
  options?: Options<GetApiScheduleClaimsData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiScheduleClaimsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiScheduleClaims({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiScheduleClaimsQueryKey(options),
  });

export const deleteApiScheduleByGuidMutation = (
  options?: Partial<Options<DeleteApiScheduleByGuidData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<DeleteApiScheduleByGuidData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<DeleteApiScheduleByGuidData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiScheduleByGuid({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiScheduleByGuidQueryKey = (
  options: Options<GetApiScheduleByGuidData>,
) => createQueryKey("getApiScheduleByGuid", options);

export const getApiScheduleByGuidOptions = (
  options: Options<GetApiScheduleByGuidData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiScheduleByGuidQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiScheduleByGuid({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiScheduleByGuidQueryKey(options),
  });

export const putApiScheduleByGuidMutation = (
  options?: Partial<Options<PutApiScheduleByGuidData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<PutApiScheduleByGuidData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PutApiScheduleByGuidData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiScheduleByGuid({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getQueryKey = (options?: Options<GetData>) =>
  createQueryKey("get", options);

export const getOptions = (options?: Options<GetData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await get({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getQueryKey(options),
  });

export const postApiScheduleMutation = (
  options?: Partial<Options<PostApiScheduleData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiScheduleData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostApiScheduleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSchedule({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
