// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  getApiClaims,
  getApiPrivate,
  getApiPrivateScoped,
  getApiPublic,
  type Options,
} from "../sdk.gen";
import type {
  GetApiClaimsData,
  GetApiPrivateData,
  GetApiPrivateScopedData,
  GetApiPublicData,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiPublicQueryKey = (options?: Options<GetApiPublicData>) =>
  createQueryKey("getApiPublic", options);

export const getApiPublicOptions = (options?: Options<GetApiPublicData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPublicQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPublicQueryKey(options),
  });

export const getApiPrivateQueryKey = (options?: Options<GetApiPrivateData>) =>
  createQueryKey("getApiPrivate", options);

export const getApiPrivateOptions = (options?: Options<GetApiPrivateData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPrivateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateQueryKey(options),
  });

export const getApiPrivateScopedQueryKey = (
  options?: Options<GetApiPrivateScopedData>,
) => createQueryKey("getApiPrivateScoped", options);

export const getApiPrivateScopedOptions = (
  options?: Options<GetApiPrivateScopedData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiPrivateScopedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivateScoped({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateScopedQueryKey(options),
  });

export const getApiClaimsQueryKey = (options?: Options<GetApiClaimsData>) =>
  createQueryKey("getApiClaims", options);

export const getApiClaimsOptions = (options?: Options<GetApiClaimsData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getApiClaimsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClaims({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiClaimsQueryKey(options),
  });
