// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  deleteApiScheduleByGuid,
  getApiAvailabilityByGuidExists,
  getApiAvailabilityPublic,
  getApiClaims,
  getApiPrivate,
  getApiPrivateScoped,
  getApiPublic,
  getApiSchedule,
  getApiScheduleByGuid,
  getApiScheduleByGuidGenerateSchedule,
  type Options,
  patchApiScheduleByGuid,
  postApiSchedule,
} from "../sdk.gen";
import type {
  DeleteApiScheduleByGuidData,
  GetApiAvailabilityByGuidData,
  GetApiAvailabilityByGuidExistsData,
  GetApiAvailabilityPublicData,
  GetApiClaimsData,
  GetApiPrivateData,
  GetApiPrivateScopedData,
  GetApiPublicData,
  GetApiScheduleByGuidCreateAvailabilityData,
  GetApiScheduleByGuidData,
  GetApiScheduleByGuidGenerateScheduleData,
  GetApiScheduleData,
  PatchApiScheduleByGuidData,
  PostApiScheduleData,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiPublicQueryKey = (options?: Options<GetApiPublicData>) => createQueryKey("getApiPublic", options);

export const getApiPublicOptions = (options?: Options<GetApiPublicData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiPublicQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPublicQueryKey(options),
  });

export const getApiPrivateQueryKey = (options?: Options<GetApiPrivateData>) => createQueryKey("getApiPrivate", options);

export const getApiPrivateOptions = (options?: Options<GetApiPrivateData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiPrivateQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateQueryKey(options),
  });

export const getApiPrivateScopedQueryKey = (options?: Options<GetApiPrivateScopedData>) =>
  createQueryKey("getApiPrivateScoped", options);

export const getApiPrivateScopedOptions = (options?: Options<GetApiPrivateScopedData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiPrivateScopedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPrivateScoped({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiPrivateScopedQueryKey(options),
  });

export const getApiClaimsQueryKey = (options?: Options<GetApiClaimsData>) => createQueryKey("getApiClaims", options);

export const getApiClaimsOptions = (options?: Options<GetApiClaimsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiClaimsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClaims({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiClaimsQueryKey(options),
  });

export const getApiAvailabilityPublicQueryKey = (options?: Options<GetApiAvailabilityPublicData>) =>
  createQueryKey("getApiAvailabilityPublic", options);

export const getApiAvailabilityPublicOptions = (options?: Options<GetApiAvailabilityPublicData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiAvailabilityPublicQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAvailabilityPublic({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAvailabilityPublicQueryKey(options),
  });

export const getApiAvailabilityByGuidExistsQueryKey = (options: Options<GetApiAvailabilityByGuidExistsData>) =>
  createQueryKey("getApiAvailabilityByGuidExists", options);

export const getApiAvailabilityByGuidExistsOptions = (options: Options<GetApiAvailabilityByGuidExistsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiAvailabilityByGuidExistsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAvailabilityByGuidExists({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAvailabilityByGuidExistsQueryKey(options),
  });

export const getApiAvailabilityByGuidQueryKey = (options: Options<GetApiAvailabilityByGuidData>) =>
  createQueryKey("getApiAvailabilityByGuid", options);

export const getApiAvailabilityByGuidOptions = (options: Options<GetApiAvailabilityByGuidData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiAvailabilityByGuidQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAvailabilityByGuid({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAvailabilityByGuidQueryKey(options),
  });

export const deleteApiScheduleByGuidMutation = (
  options?: Partial<Options<DeleteApiScheduleByGuidData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteApiScheduleByGuidData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiScheduleByGuidData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiScheduleByGuid({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiScheduleByGuidQueryKey = (options: Options<GetApiScheduleByGuidData>) =>
  createQueryKey("getApiScheduleByGuid", options);

export const getApiScheduleByGuidOptions = (options: Options<GetApiScheduleByGuidData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiScheduleByGuidQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiScheduleByGuid({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiScheduleByGuidQueryKey(options),
  });

export const patchApiScheduleByGuidMutation = (
  options?: Partial<Options<PatchApiScheduleByGuidData>>,
): UseMutationOptions<unknown, DefaultError, Options<PatchApiScheduleByGuidData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiScheduleByGuidData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchApiScheduleByGuid({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiScheduleQueryKey = (options?: Options<GetApiScheduleData>) =>
  createQueryKey("getApiSchedule", options);

export const getApiScheduleOptions = (options?: Options<GetApiScheduleData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiScheduleQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSchedule({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiScheduleQueryKey(options),
  });

export const postApiScheduleMutation = (
  options?: Partial<Options<PostApiScheduleData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostApiScheduleData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiScheduleData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSchedule({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiScheduleByGuidGenerateScheduleQueryKey = (
  options: Options<GetApiScheduleByGuidGenerateScheduleData>,
) => createQueryKey("getApiScheduleByGuidGenerateSchedule", options);

export const getApiScheduleByGuidGenerateScheduleOptions = (
  options: Options<GetApiScheduleByGuidGenerateScheduleData>,
) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiScheduleByGuidGenerateScheduleQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiScheduleByGuidGenerateSchedule({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiScheduleByGuidGenerateScheduleQueryKey(options),
  });
