// <auto-generated />
using System;
using LineUp.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LineUp.Backend.Migrations
{
    [DbContext(typeof(LineUpContext))]
    [Migration("20260318063002_AddScheduleFkId")]
    partial class AddScheduleFkId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LineUp.Core.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<DateTime[]>("AvailabilitySlots")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreferencesId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Guid");

                    b.HasIndex("PreferencesId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("LineUp.Core.Models.AvailabilityPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityPreferences");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.FormQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormQuestions");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.FormQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("integer");

                    b.Property<int>("FormQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("FormQuestionId");

                    b.ToTable("FormQuestionAnswers");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.QuestionOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("LineUp.Core.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<DateOnly[]>("DateCoverage")
                        .IsRequired()
                        .HasColumnType("date[]");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SchedulePreferencesId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormId")
                        .IsUnique();

                    b.HasIndex("SchedulePreferencesId");

                    b.HasIndex("Auth0UserId", "Guid");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LineUp.Core.Models.SchedulePreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumShiftDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumShiftsPerWorker")
                        .HasColumnType("integer");

                    b.Property<int>("MinutesPerSlot")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftIntervals")
                        .HasColumnType("integer");

                    b.Property<int>("UsersPerShift")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SchedulePreferences");
                });

            modelBuilder.Entity("LineUp.Core.Models.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("LineUp.Core.Models.Availability", b =>
                {
                    b.HasOne("LineUp.Core.Models.AvailabilityPreferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferencesId");

                    b.HasOne("LineUp.Core.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preferences");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.FormQuestion", b =>
                {
                    b.HasOne("LineUp.Core.Models.Forms.Form", null)
                        .WithMany("Questions")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.FormQuestionAnswer", b =>
                {
                    b.HasOne("LineUp.Core.Models.Availability", null)
                        .WithMany("FormAnswers")
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("LineUp.Core.Models.Forms.FormQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("FormQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.QuestionOptions", b =>
                {
                    b.HasOne("LineUp.Core.Models.Forms.FormQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("FormQuestionId");
                });

            modelBuilder.Entity("LineUp.Core.Models.Schedule", b =>
                {
                    b.HasOne("LineUp.Core.Models.Forms.Form", "Form")
                        .WithOne("Schedule")
                        .HasForeignKey("LineUp.Core.Models.Schedule", "FormId");

                    b.HasOne("LineUp.Core.Models.SchedulePreferences", "SchedulePreferences")
                        .WithMany()
                        .HasForeignKey("SchedulePreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("SchedulePreferences");
                });

            modelBuilder.Entity("LineUp.Core.Models.ShiftAssignment", b =>
                {
                    b.HasOne("LineUp.Core.Models.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("LineUp.Core.Models.Schedule", null)
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Availability");
                });

            modelBuilder.Entity("LineUp.Core.Models.Availability", b =>
                {
                    b.Navigation("FormAnswers");
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.Form", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("LineUp.Core.Models.Forms.FormQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LineUp.Core.Models.Schedule", b =>
                {
                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
