// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LineUp.Backend.Migrations
{
    [DbContext(typeof(LineUpContext))]
    [Migration("20260218033303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LineUp.Backend.Models.Availability", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<Guid>("PreferencesID")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly[,]>("availability")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.HasKey("ID");

                    b.HasIndex("PreferencesID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Preferences", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Schedule", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("authToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<DateOnly[]>("dateCoverage")
                        .IsRequired()
                        .HasColumnType("date[]");

                    b.PrimitiveCollection<TimeOnly[]>("hourCoverage")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.Property<Guid>("preferencesID")
                        .HasColumnType("uuid");

                    b.Property<string[,]>("shiftAssignment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<bool[]>("weekdayCoverage")
                        .IsRequired()
                        .HasColumnType("boolean[]");

                    b.HasKey("ID");

                    b.HasIndex("preferencesID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Availability", b =>
                {
                    b.HasOne("LineUp.Backend.Models.Preferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferencesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineUp.Backend.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleID");

                    b.Navigation("Preferences");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Schedule", b =>
                {
                    b.HasOne("LineUp.Backend.Models.Preferences", "preferences")
                        .WithMany()
                        .HasForeignKey("preferencesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
