// <auto-generated />
using System;
using LineUp.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LineUp.Backend.Migrations
{
    [DbContext(typeof(LineUpContext))]
    [Migration("20260220041858_MinutesPerSlot")]
    partial class MinutesPerSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LineUp.Backend.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<DateTime[]>("AvailabilitySlots")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<Guid?>("PreferencesId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreferencesId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("LineUp.Backend.Models.AvailabilityPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AvailabilityPreferences");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<DateOnly[]>("DateCoverage")
                        .IsRequired()
                        .HasColumnType("date[]");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchedulePreferencesId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.PrimitiveCollection<bool[]>("WeekdayCoverage")
                        .IsRequired()
                        .HasColumnType("boolean[]");

                    b.HasKey("Id");

                    b.HasIndex("SchedulePreferencesId");

                    b.HasIndex("Auth0UserId", "Guid");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LineUp.Backend.Models.SchedulePreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MinutesPerSlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SchedulePreferences");
                });

            modelBuilder.Entity("LineUp.Backend.Models.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ShiftAssignment");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Availability", b =>
                {
                    b.HasOne("LineUp.Backend.Models.AvailabilityPreferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferencesId");

                    b.HasOne("LineUp.Backend.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preferences");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Schedule", b =>
                {
                    b.HasOne("LineUp.Backend.Models.SchedulePreferences", "SchedulePreferences")
                        .WithMany()
                        .HasForeignKey("SchedulePreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchedulePreferences");
                });

            modelBuilder.Entity("LineUp.Backend.Models.ShiftAssignment", b =>
                {
                    b.HasOne("LineUp.Backend.Models.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineUp.Backend.Models.Schedule", "Schedule")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LineUp.Backend.Models.Schedule", b =>
                {
                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
