name: docs

on:
  push:
    branches: [ "main" ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.31.0
      - name: Build JS docs
        run: |
          cd lineup-client
          pnpm install
          pnpm exec typedoc
          cp client-toc.yml docs/toc.yml
      - name: Restore dependencies
        run: dotnet restore && dotnet tool restore
      - name: Build Documentation
        run: dotnet docfx docfx.json
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: _site/


  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # or specific "vX.X.X" version tag for this action
